version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: api
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://pedro:12345@db:5432/risevest_test
      - SECRET_JWT_KEY=hX3a2Df5Kr8zLj9pT4wQm1Vc6GyN7vXe
    networks:
      - default
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app

  db:
    image: postgres:16.3
    container_name: database
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      POSTGRES_USER: pedro
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DB: risevest_test
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
  default:
    driver: bridge
