version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: api
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_JWT_KEY=${SECRET_JWT_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      - default
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "npm install &&
             npx prisma migrate deploy &&
             npx prisma generate &&
             npm run start:dev"

  db:
    image: postgres:16.3
    container_name: database
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      POSTGRES_USER: pedro
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: risevest_test
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    container_name: keycloak
    ports:
      - "8080:8080"
    networks:
      - default
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${DB_USER}
      - KC_DB_PASSWORD=${DB_PASSWORD}
      - KC_HOSTNAME=${DB}
    command: start-dev
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:

networks:
  default:
    driver: bridge
