version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: api
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_JWT_KEY=${SECRET_JWT_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      - default
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: >
      sh -c "npm install &&
             npx prisma migrate deploy &&
             npx prisma generate &&
             npm run start:dev"

  db:
    image: postgres:16.3
    container_name: database
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      POSTGRES_USER: pedro
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: risevest_test
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
  default:
    driver: bridge
